[project]
name = "day05"
version = "0.1.0"
description = ""
authors = [
    {name = "Rich Clubb",email = "rich.clubb@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "python", from = "src"}]

[tool.poetry.scripts]
day05 = "python src/main.py:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.1.0,<27.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "ruff (>=0.15.0,<0.16.0)"
]
